### ISSUE TITLE
diamond takes a while to stop, errors out, slows down shutdown

### ISSUE THREAD

**Issue by sandrotosi** [python-diamond/Diamond#595]
Hello,
as reported in Debian at http://bugs.debian.org/854842

```
In my setup, diamond takes a long time to stop after getting a SIGTERM
from systemd, thus slowing down the overall shutdown of the system by
about a minute (and also making it slow to perform restarts). When it
finally does stop, an error message about QueueHandler is emitted. The
issue is reproducible without systemd too -- run diamond in one terminal
with --log-stdout --foreground and then run kill from another terminal
(Ctrl+C i.e. SIGINT won't reproduce it). This happens even with a
relatively minimal config, e.g. without any Collectors defined and only
with a single GraphiteHandler.

What I see here is:
root@d-i-test:/etc/diamond# diamond --log-stdout --foreground
1486775151.66   [MainProcess:9336:INFO] Changed UID: 0 () GID: 0 ().
1486775152.06   [MainProcess:9336:DEBUG]        metric_queue_size: 16384
1486775152.06   [MainProcess:9336:DEBUG]        Loading Handler diamond.handler.graphite.GraphiteHandler
1486775152.1    [MainProcess:9336:DEBUG]        GraphiteHandler: Established connection to graphite server 10.192.16.33:2003.
1486775152.11   [Handlers:9347:DEBUG]   Starting process Handlers
1486775153.12   [TCPCollector:9350:DEBUG]       Starting
1486775153.12   [TCPCollector:9350:DEBUG]       Interval: 60.0 seconds
1486775153.13   [TCPCollector:9350:DEBUG]       Max collection time: 28 seconds
1486775153.16   [TCPCollector:9350:DEBUG]       Collection took 32 ms
1486775154.14   [NetworkCollector:9353:DEBUG]   Starting
1486775154.14   [NetworkCollector:9353:DEBUG]   Interval: 60.0 seconds
1486775154.14   [NetworkCollector:9353:DEBUG]   Max collection time: 19 seconds
1486775154.16   [NetworkCollector:9353:DEBUG]   Collection took 16 ms
1486775155.15   [DiskUsageCollector:9356:DEBUG] Starting
1486775155.15   [DiskUsageCollector:9356:DEBUG] Interval: 60.0 seconds
1486775155.15   [DiskUsageCollector:9356:DEBUG] Max collection time: 48 seconds
1486775155.15   [DiskUsageCollector:9356:DEBUG] Collection took 1 ms
1486775156.16   [CPUCollector:9359:DEBUG]       Starting
1486775156.16   [CPUCollector:9359:DEBUG]       Interval: 60.0 seconds
1486775156.16   [CPUCollector:9359:DEBUG]       Max collection time: 43 seconds
1486775156.17   [CPUCollector:9359:DEBUG]       Collection took 7 ms
<send kill from another terminal>
1486775186.96   [MainProcess:9336:INFO] Signal Received: 15
1486775186.96   [NetworkCollector:9353:INFO]    Signal Received: 15
1486775186.96   [Handlers:9347:INFO]    Signal Received: 15
1486775186.96   [DiskUsageCollector:9356:INFO]  Signal Received: 15
1486775186.96   [TCPCollector:9350:INFO]        Signal Received: 15
1486775186.96   [CPUCollector:9359:INFO]        Signal Received: 15
1486775186.97   [NetworkCollector:9353:INFO]    Signal Received: 15
1486775186.97   [CPUCollector:9359:INFO]        Signal Received: 15
<long wait>
Exception socket.error: error(111, 'Connection refused') in <bound method QueueHandler.__del__ of <diamond.handler.queue.QueueHandler object at 0x7f8fa53bff10>> ignored

While this long wait is happening, strace shows diamond is busylooping
running this over and over (apparently python multiprocessing related):
connect(4, {sa_family=AF_UNIX, sun_path="/tmp/pymp-xq1DKs/listener-8_h02F"}, 34) = -1 ECONNREFUSED (Connection refused)
close(4)                                = 0
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=10000}) = 0 (Timeout)
socket(AF_UNIX, SOCK_STREAM, 0)         = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR)               = 0
```

could you have a look at this? thanks!

**Comment by sandrotosi** [comment]
@paravoid

**Comment by DStape** [comment]
I have a fix for this: https://github.com/python-diamond/Diamond/pull/611

**Comment by shortdudey123** [comment]
@sandrotosi Fixed via https://github.com/python-diamond/Diamond/pull/611

**Comment by paravoid** [comment]
This is actually still broken when running diamond under systemd. I think this is because systemd by default sends a SIGTERM (eventually followed by a SIGKILL) to all processes in the service's cgroup (so here: all Diamond subprocesses) and that is still broken (racy?) even under the new code.

I can confirm that the new code makes diamond stop immediately when killing the parent (first) diamond process, but fails when killed in a systemd-like fashion. This is easy to reproduce by running `/usr/bin/diamond --log-stdout --foreground` in one terminal and `pkill -f diamond` in another ­­-- still broken. Conversely, in the systemd service, if you pass `KillMode=mixed` (which makes systemd only send a TERM to the parent, followed by a KILL in all processes), things work as expected.

I believe this is still a diamond bug and shouldn't be worked around with a systemd `KillMode` argument.

Also, semi-relatedly: if you `kill -TERM` a random subprocess and not the parent, it gets immediately respawned and everything still works:
```
1487809147.54	[NetworkCollector:12912:INFO]	Signal Received: 15
1487809149.44	[NetworkCollector:12926:DEBUG]	Starting
```
…but when you finally kill the parent, you still get:
```
Exception socket.error: error(2, 'No such file or directory') in <bound method QueueHandler.__del__ of <diamond.handler.queue.QueueHandler object at 0x7fe834aa8ed0>> ignored
```

**Comment by shortdudey123** [comment]
> This is easy to reproduce by running /usr/bin/diamond --log-stdout --foreground in one terminal and pkill -f diamond in another ­­-- still broken

I am unable to reproduce this.  When running `pkill -f diamond`, the processes are killed affectively instantly.  Can you provide more info? config?

**Comment by DStape** [comment]
Thanks for that info, I'll take another look at this.

My current understanding of the process model is as follows:

i) main process
ii) SyncManager spawned by main process
iii) Handler process spawned by main
iv) Collector process(es) also spawned by main

Each collector runs in its own process space, so if no collectors are configured, there are no collector processes. As a result, there is always a minimum of 3 processes running (see below).

There's only one handler process used for executing all configured handlers. If no handlers are configured, this process still exists. If 99999... handlers are configured, they all run within this same process.

There is some code in src/diamond/server.py that's executed by the main process and it checks configured collectors vs running collectors and re-spawns any that aren't running - I'd guess this is what you're seeing when randomly killing subprocesses, although I'm not 100% on that. Collectors are always spawned last, so this can be tested out by aiming the SIGTERM at the first two processes created by main and seeing if those re-spawn. If they do, I dunno what's happening and need to take another look at the code. I'm relatively new to Diamond so still learning about its internals :)

**Comment by paravoid** [comment]
So the fix above basically modified the signal handler to skip the SyncManager process while looping over all the children and terminating them, essentially leaving it to die when the master process sys.exit()s.

I think what's happening here is that the signal handlers for SIGINT/SIGTERM are being installed *before* any processes are being spawned and as such they are being inherited by all the children, including SyncManager. When e.g. systemd sends a TERM to all processes, the SyncManager process gets one as well and proceeds to immediately die, recreating the original issue.

I tried working around this, as a hack by wrapping the `Manager()`  instatiation as such:
```
-->     original_handler = signal.getsignal(signal.SIGTERM)
-->     signal.signal(signal.SIGTERM, signal.SIG_IGN)

        # We do this weird process title swap around to get the sync manager
        # title correct for ps
        if setproctitle:
            oldproctitle = getproctitle()
            setproctitle('%s - SyncManager' % getproctitle())
        self.manager = multiprocessing.Manager()
        if setproctitle:
            setproctitle(oldproctitle)

-->     signal.signal(signal.SIGTERM, original_handler)
```

This seems to have done the trick, although I think it's a bit of a hack as we set and unset the signal handler twice (it also doesn't cover SIGINT yet!). Moreover, it's not changing the behavior for any of the other children, but these probably need their own signal handler as well, so that they can exit themselves, but not loop over all processes like the parent one does.

In general, right now signal handlers are be installed in two places (server.py for HUP and the main binary for INT/TERM), one of which handles it in a special way (by the way of `signal_to_exception`) and that's a little messy. Properly fixing the code probably requires SIGTERM/INT handling in three different ways (looping over all children for the master process, ignoring it for the manager, just exiting for handlers/collectors), plus the HUP handling for config reloads. I've spent all of 10 minutes with the code so it's hard for me to pass any advice but intuitively it would make sense to me to centralize signal handling in one place and do it in one way (either functions or exceptions).

PS. Nothing very special with my config -- just one handler (Graphite) and four collectors (CPU, DiskUsage, Network, TCP).

**Comment by DStape** [comment]
The parent process interprets SIGINTs and SIGTERMs as shutdown requests. Commit fd4146d fixes the problem where the Manager process can exit before the others which then causes them to crash.

The parent process also has a SIGHUP handler set up and interprets this signal as a request to reload its config. That seems to work fine.

That said, I do agree that the signal handler setup code should be refactored so that it's all done in the same place and using the same mechanism. However, to fix/close the issue described here, combined with fd4146d, the service file should be modified so that a 'service stop' should only send a SIGTERM to the main process.

I've started playing around with this and should hopefully be in a position to make another PR soon.

Thanks.

**Comment by paravoid** [comment]
Not sure if we're talking past each other, so forgive the verbosity :)

Commit fd4146d fixes the problem where the Manager process can exit before the others //if you send the TERM to the parent process//. It doesn't address the issue where you send a TERM to the Manager process itself (either alone or in combination with the parent, e.g. like systemd does). As the code is set up right now, the signal handler is installed in all children, including the Manager process, and ends with `sys.exit(0)`, so the Manager process will die when instructed with a TERM. The snipped I pasted above sets up the Manager process (and only the Manager process) to ignore SIGTERM and it only works in combination with fd4146d.

**Comment by DStape** [comment]
:)

Yes, it doesn't address sending TERM to the manager (or to any of the other processes, I haven't experimented with that so don't know what the behavior is).

So I guess it depends on what we think is the "right" way to shutdown diamond. In my opinion, correctly shutting down the daemon should only be done by signaling to the main process. It's then the responsibility of the main process to cleanly terminate its children. If signals are sent to the child processes - then that's the wrong thing to do (again, only imo). (I do however think that the child processes should be made more robust and explciitly deal with receiving signals, but that's an improvement rather than a fix for this particular issue.)

What do you think?

**Comment by paravoid** [comment]
I think we're in agreement. I think the proper behavior is that if you send a TERM to one of the children:
- diamond as a whole won't die
- diamond won't start misbehaving (busy loops, exceptions printed out etc.)

That's the case for the most part here. The `while True` loop actually respawns processes that should be running -- with the exception of SyncManager of course.

As such, I think Diamond should be coded so that the signal handler currently found in the "main" binary only runs on the main process. The SyncManager process should probably have SIG_IGN for TERM/INT, and the rest of the children should probably have a signal handler to allow them to just die gracefully themselves without the code for enumerating over multiprocessing processes at all like they have now.

**Comment by DStape** [comment]
The only problem I see is in relation to the collector processes. The main process will respawn a collector if it sees that it's no longer alive (~every 1 second). This behaviour was added by commit 2025384. Therefore, I'm not sure it'll be possible for collectors to gracefully terminate themselves, since the main process will respawn it when it detects its no longer running. This can get a little messy since I don't think the control-group KillMode can guarantee sending signals in an ordered fashion, since ideally we'd like the main process to die first, so that it doesn't get the chance to respawn a collector. Essentially, we'd be adding a new race condition.

Therefore, unless we remove the 're-load collector if it crashes' behaviour, I'm not sure this is the best approach. IMO, to fix this specific issue, we need the service file to set KillMode to 'process'. That way, combined with fd4146d, all diamond processes will be gracefully shutdown:

i) SIGTERM will be sent to the main process. 
ii) collectors and handlers will then be terminated within for loop in shutdown_handler()
iii) main process will exit
iv) SyncManager will then exit.

I think a separate issue can be created for tidying up signal handlers.

What are your thoughts on this?

**Comment by DStape** [comment]
@sandrotosi The only diamond.service file I see in this repo is in Diamond/rpm/systemd/diamond.service which differs from the one shipped in Debian. I'm assuming you maintain this elsewhere? Would it be possible to update this so that KillMode is set to 'process'? Thanks.

**Comment by sandrotosi** [comment]
yes @DStape we maintain the service file at https://anonscm.debian.org/viewvc/python-apps/packages/diamond/trunk/debian/diamond.service?view=markup

@paravoid could you have a look if these 2 changes address your usecase?

**Comment by DStape** [comment]
Thanks @sandrotosi .

@paravoid , do you have any further comments on this? Thanks.

**Comment by DStape** [comment]
Any further comments on this @paravoid? @sandrotosi , would really appreciate these changes being made available in Debian. Thanks.

**Comment by paravoid** [comment]
Sorry for the late reply. I think in the short-term `KillMode=mixed` in the unit would work, but I definitely still think that the signal handlers should be cleaned up as described above.

That said, I'm currently unable to reproduce this bug anymore and I'm completely unsure why! I've tried reproducing it both with systemd and like I did before, with `pkill -f` and everything stops immediately. I still have the same collectors and handlers as before. This may be a race, but I'm not sure why the race always resulted in a failure before and always in success now; perhaps a collector suddenly became more responsive or something…

**Comment by filippog** [comment]
I was able to reproduce this behaviour when testing diamond 4.0.515 on stretch (and jessie), though the patch @Ssawa proposed above fixed it for us (i.e. stopping went from 20s to immediate). There's also a little more context on https://phabricator.wikimedia.org/T97635

**Comment by DStape** [comment]
Hi @filippog, thanks for letting us know.

@paravoid, I'd be happy to look at making the signal handler changes, however I unfortunately don't have the time to do that just now and I'd really like to see this available in debian. [Commit fd4146d](https://github.com/python-diamond/Diamond/commit/fd4146dc30434d1ea6539d411d88ddf105061011) (same one referenced by @filippog) fixes the issue reported here.
